version: '2'

services:
    #
    # Drop master
    #
    master-rest-api:
        image: nginx
        ports:
            - 15000:80
        volumes:
            - ./services/drop-master/:/var/www/html/
            - ./services/drop-master/docker/rest-api/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - master-php-fpm:php-fpm

    master-websocket-server:
        container_name: master-sandstone-ws
        build: services/drop-master/docker/php-fpm
        command: php bin/websocket-server
        ports:
            - 15002:8482
        volumes:
            - ./services/drop-master/:/var/www/html/

    master-php-fpm:
        container_name: master-sandstone-php
        build: services/drop-master/docker/php-fpm
        environment:
            FLEET_CONTROL_API: http://fleetcontrol-rest-api/
            API_KEY: "${API_KEY}"
        volumes:
            - ./services/drop-master/:/var/www/html/
        links:
            - master-database:database
            - master-websocket-server:websocket-server
            - fleetcontrol-rest-api

    master-database:
        container_name: master-sandstone-database
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root

    master-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: master-database
        ports:
            - 15001:80

    #
    # Fleet control
    #
    fleetcontrol-php-fpm:
        build: services/drop-fleetcontrol-master/docker/php-fpm
        container_name: fleetcontrol-master-php
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            RABBITMQ_USER: guest
            RABBITMQ_PASS: guest
            RABBITMQ_EXCHANGE: orders
        volumes:
            - ./services/drop-fleetcontrol-master/:/var/www/html/
        working_dir: /var/www/html/
        links:
            - rabbitmq

    fleetcontrol-rest-api:
        image: nginx:latest
        ports:
            - 11000:80
        volumes:
            - ./services/drop-fleetcontrol-master/:/var/www/html/
            - ./services/drop-fleetcontrol-master/docker/rest-api/nginx.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html/
        links:
            - fleetcontrol-php-fpm:php-fpm

    #
    # Twitter observer temporary
    #
    observer-php-fpm:
        build: services/drop-fleetcontrol-master/docker/php-fpm
        container_name: observer-php
        environment:
            MASTER_API:             http://master-rest-api/index-dev.php/api/
            HASHTAG:                "${HASHTAG}"
            MASTER_API_KEY:         "${API_KEY}"
            ACCESS_TOKEN:           "${ACCESS_TOKEN}"
            ACCESS_TOKEN_SECRET:    "${ACCESS_TOKEN_SECRET}"
            CONSUMER_KEY:           "${CONSUMER_KEY}"
            CONSUMER_SECRET:        "${CONSUMER_SECRET}"
        command: sh -c "composer install && php run.php"
        volumes:
            - ./services/drop-observer-tmp/:/var/www/html/
        working_dir: /var/www/html/
        links:
            - master-rest-api

    #
    # RabbitMQ
    #
    rabbitmq:
        image: rabbitmq:3.7.3-management-alpine
        ports:
            - 12000:5672
            - 12001:15672
